apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-170208097
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/v9hf6grc-tenant/test-app-170208097/go-170208097@sha256:787d945878df21802b3a2e782020448c35f36771580b6fa76b9d6c9b5169be36
        name: my-go
        resources: {}
status: {}
