apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-170208097
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/v9hf6grc-tenant/test-app-170208097/go-170208097@sha256:101ce7f70a45e7ba11822ce90a17258296e10002e832ac969b561737cf433ce5
        name: my-go
        resources: {}
status: {}
